<?php


return [

    'company_list'=> [
        "PROBE ADVISORY AND SOLUTION PRIVATE LIMITED",
        "PROBE CONSULTANTS PRIVATE LTD",
        "PROBE DEALCOM PRIVATE LIMITED",
        "PROBE DEALERS PRIVATE LIMITED",
        "PROBE DETECTIVE AND SECURITY PRIVATE LIMITED",
        "PROBE DIAGNOSTIC PRIVATE LIMITED",
        "PROBE DIGITAL PRIVATE LIMITED",
        "PROBE DISTRIBUTORS PRIVATE LIMITED",
        "PROBE ELECTRONICS PRIVATE LIMITED",
        "PROBE EYE PRIVATE LIMITED",
        "PROBE HYGIENIC PRODUCTS LIMITED",
        "PROBE INFORMATION SERVICES PRIVATE LIMITED",
        "PROBE INSURANCE CONSULTANTS PRIVATE LIMITED",
        "PROBE INVESTMENTS PRIVATE LIMITED",
        "PROBE MARKET RESEARCH AND CONSULTANCY (INDIA) PRIVATE LIMITED",
        "PROBE MARKETINGS PRIVATE LIMITED",
        "PROBE MEDICAL AND DIAGNOSTIC CENTRE PRIVATE LIMITED",
        "PROBE PORTFOLIO & CREDITS PRIVATE LIMITED",
        "PROBE RESEARCH & SOCIAL DEVELOPMENT PRIVATE LIMITED",
        "PROBE SERVICES PRIVATE LIMITED",
        "PROBE SOFTWARE PRIVATE LIMITED",
        "PROBEL ENTERPRISES PRIVATE LIMITED",
        "PROBENCHMARK OUTSOURCING SOLUTIONS (INDIA) PRIVATE LIMITED",
        "PROBEPLUS INNOVATIVE SOLUTIONS PRIVATE LIMITED",
        "PROBEST PHARMA PRIVATE LIMITED"
    ],
    

];